// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/api/joke.ts";
import * as $2 from "./routes/index.tsx";
import * as $3 from "./routes/posts/[slug].tsx";
import * as $$0 from "./islands/Donate.tsx";
import * as $$1 from "./islands/Footer.tsx";
import * as $$2 from "./islands/Nav.tsx";
import * as $$3 from "./islands/PostCard.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/api/joke.ts": $1,
    "./routes/index.tsx": $2,
    "./routes/posts/[slug].tsx": $3,
  },
  islands: {
    "./islands/Donate.tsx": $$0,
    "./islands/Footer.tsx": $$1,
    "./islands/Nav.tsx": $$2,
    "./islands/PostCard.tsx": $$3,
  },
  baseUrl: import.meta.url,
};

export default manifest;
