// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/about.tsx";
import * as $2 from "./routes/bg.svg.ts";
import * as $3 from "./routes/blooper.tsx";
import * as $4 from "./routes/index.tsx";
import * as $5 from "./routes/posts.tsx";
import * as $6 from "./routes/posts/[slug].tsx";
import * as $7 from "./routes/sitemap.xml.ts";
import * as $$0 from "./islands/WaterDrop.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/about.tsx": $1,
    "./routes/bg.svg.ts": $2,
    "./routes/blooper.tsx": $3,
    "./routes/index.tsx": $4,
    "./routes/posts.tsx": $5,
    "./routes/posts/[slug].tsx": $6,
    "./routes/sitemap.xml.ts": $7,
  },
  islands: {
    "./islands/WaterDrop.tsx": $$0,
  },
  baseUrl: import.meta.url,
};

export default manifest;
