export function AnimatedSVGBack(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      version="1.1"
      xmlns="http://www.w3.org/2000/svg"
      xmlnsXlink="http://www.w3.org/1999/xlink"
      x="0px"
      y="0px"
      width="1800px"
      height="1200px"
      viewBox="0 0 1800 1200"
      enableBackground="new 0 0 1800 1200"
      xmlSpace="preserve"
      {...props}
    >
      <rect
        x="-24.273"
        y="-21.243"
        fill="transparent"
        stroke="none"
        strokeMiterlimit="10"
        width="1842.184"
        height="1233.123"
      />

      <circle
        opacity="0"
        fill="none"
        stroke="#5EEAD4"
        strokeWidth="2"
        strokeMiterlimit="10"
        cx="127.754"
        cy="113.781"
        r="13"
      >
        <animate
          attributeName="opacity"
          values="0;.6;0"
          begin="0s"
          dur="3s"
          repeatCount="indefinite"
        />
      </circle>
      <circle
        opacity="0"
        fill="none"
        stroke="#2DD4BF"
        strokeWidth="2"
        strokeMiterlimit="10"
        cx="365"
        cy="249.997"
        r="22"
      >
        <animate
          attributeName="opacity"
          values="0;.6;0"
          begin=".2s"
          dur="2s"
          repeatCount="indefinite"
        />
      </circle>
      <circle
        opacity="0"
        fill="none"
        stroke="#14B8A6"
        strokeWidth="2"
        strokeMiterlimit="10"
        cx="547"
        cy="387.997"
        r="18"
      >
        <animate
          attributeName="opacity"
          values="0;.6;0"
          begin=".4s"
          dur="4s"
          repeatCount="indefinite"
        />
      </circle>
      <circle
        opacity="0"
        fill="none"
        stroke="#2DD4BF"
        strokeWidth="2"
        strokeMiterlimit="10"
        cx="125"
        cy="509.997"
        r="18"
      >
        <animate
          attributeName="opacity"
          values="0;.6;0"
          begin=".6s"
          dur="5s"
          repeatCount="indefinite"
        />
      </circle>
      <circle
        opacity="0"
        fill="none"
        stroke="#5EEAD4"
        strokeWidth="2"
        strokeMiterlimit="10"
        cx="663.754"
        cy="125.781"
        r="14"
      >
        <animate
          attributeName="opacity"
          values="0;.6;0"
          begin=".8s"
          dur="3s"
          repeatCount="indefinite"
        />
      </circle>
      <circle
        opacity="0"
        fill="none"
        stroke="#5EEAD4"
        strokeWidth="2"
        strokeMiterlimit="10"
        cx="505.754"
        cy="595.781"
        r="10"
      >
        <animate
          attributeName="opacity"
          values="0;.6;0"
          begin="1s"
          dur="6s"
          repeatCount="indefinite"
        />
      </circle>
      <circle
        opacity="0"
        fill="none"
        stroke="#2DD4BF"
        strokeWidth="2"
        strokeMiterlimit="10"
        cx="521.754"
        cy="909.781"
        r="12"
      >
        <animate
          attributeName="opacity"
          values="0;.6;0"
          begin="1.2s"
          dur="5s"
          repeatCount="indefinite"
        />
      </circle>
      <circle
        opacity="0"
        fill="none"
        stroke="#2DD4BF"
        strokeWidth="2"
        strokeMiterlimit="10"
        cx="219.754"
        cy="1063.781"
        r="19"
      >
        <animate
          attributeName="opacity"
          values="0;.6;0"
          begin="1.4s"
          dur="4s"
          repeatCount="indefinite"
        />
      </circle>
      <circle
        opacity="0"
        fill="none"
        stroke="#5EEAD4"
        strokeWidth="2"
        strokeMiterlimit="10"
        cx="851"
        cy="531.997"
        r="23"
      >
        <animate
          attributeName="opacity"
          values="0;.6;0"
          begin="1.6s"
          dur="5s"
          repeatCount="indefinite"
        />
      </circle>
      <circle
        opacity="0"
        fill="none"
        stroke="#14B8A6"
        strokeWidth="2"
        strokeMiterlimit="10"
        cx="941"
        cy="791.997"
        r="17"
      >
        <animate
          attributeName="opacity"
          values="0;.6;0"
          begin="1.8s"
          dur="3s"
          repeatCount="indefinite"
        />
      </circle>
      <circle
        opacity="0"
        fill="none"
        stroke="#5EEAD4"
        strokeWidth="2"
        strokeMiterlimit="10"
        cx="959.754"
        cy="235.781"
        r="16"
      >
        <animate
          attributeName="opacity"
          values="0;.6;0"
          begin="2s"
          dur="2s"
          repeatCount="indefinite"
        />
      </circle>
      <circle
        opacity="0"
        fill="none"
        stroke="#2DD4BF"
        strokeWidth="2"
        strokeMiterlimit="10"
        cx="1303.754"
        cy="151.781"
        r="22"
      >
        <animate
          attributeName="opacity"
          values="0;.6;0"
          begin="2.2s"
          dur="4s"
          repeatCount="indefinite"
        />
      </circle>
      <circle
        opacity="0"
        fill="none"
        stroke="#14B8A6"
        strokeWidth="2"
        strokeMiterlimit="10"
        cx="1229.754"
        cy="521.781"
        r="16"
      >
        <animate
          attributeName="opacity"
          values="0;.6;0"
          begin="2.4s"
          dur="5s"
          repeatCount="indefinite"
        />
      </circle>
      <circle
        opacity="0"
        fill="none"
        stroke="#2DD4BF"
        strokeWidth="2"
        strokeMiterlimit="10"
        cx="1561.997"
        cy="497"
        r="20"
      >
        <animate
          attributeName="opacity"
          values="0;.6;0"
          begin="2.6s"
          dur="4s"
          repeatCount="indefinite"
        />
      </circle>
      <circle
        opacity="0"
        fill="none"
        stroke="#14B8A6"
        strokeWidth="2"
        strokeMiterlimit="10"
        cx="1635.754"
        cy="147.781"
        r="18"
      >
        <animate
          attributeName="opacity"
          values="0;.6;0"
          begin="2.8s"
          dur="5s"
          repeatCount="indefinite"
        />
      </circle>
      <circle
        opacity="0"
        fill="none"
        stroke="#5EEAD4"
        strokeWidth="2"
        strokeMiterlimit="10"
        cx="763"
        cy="1083.997"
        r="10"
      >
        <animate
          attributeName="opacity"
          values="0;.6;0"
          begin="3s"
          dur="3s"
          repeatCount="indefinite"
        />
      </circle>
      <circle
        opacity="0"
        fill="none"
        stroke="#2DD4BF"
        strokeWidth="2"
        strokeMiterlimit="10"
        cx="1203.754"
        cy="1035.781"
        r="15"
      >
        <animate
          attributeName="opacity"
          values="0;.6;0"
          begin="3.2s"
          dur="5s"
          repeatCount="indefinite"
        />
      </circle>
      <circle
        opacity="0"
        fill="none"
        stroke="#14B8A6"
        strokeWidth="2"
        strokeMiterlimit="10"
        cx="1409.754"
        cy="821.781"
        r="20"
      >
        <animate
          attributeName="opacity"
          values="0;.6;0"
          begin="3.4s"
          dur="3s"
          repeatCount="indefinite"
        />
      </circle>
      <circle
        opacity="0"
        fill="none"
        stroke="#14B8A6"
        strokeWidth="2"
        strokeMiterlimit="10"
        cx="1661.754"
        cy="709.781"
        r="18"
      >
        <animate
          attributeName="opacity"
          values="0;.6;0"
          begin="3.6s"
          dur="2s"
          repeatCount="indefinite"
        />
      </circle>
      <circle
        opacity="0"
        fill="none"
        stroke="#5EEAD4"
        strokeWidth="2"
        strokeMiterlimit="10"
        cx="1591.754"
        cy="1017.781"
        r="10"
      >
        <animate
          attributeName="opacity"
          values="0;.6;0"
          begin="3.8s"
          dur="5s"
          repeatCount="indefinite"
        />
      </circle>
      <circle
        opacity="0"
        fill="none"
        stroke="#14B8A6"
        strokeWidth="2"
        strokeMiterlimit="10"
        cx="163.754"
        cy="827.781"
        r="15"
      >
        <animate
          attributeName="opacity"
          values="0;.6;0"
          begin="4s"
          dur="3s"
          repeatCount="indefinite"
        />
      </circle>
    </svg>
  );
}
